-- -------------------------------
-- BORRADO DE TABLAS
-- -------------------------------

DROP TABLE DETALLE_PEDIDO;
DROP TABLE PEDIDOS;
DROP TABLE PRODUCTOS;
DROP TABLE CATEGORIAS;
DROP TABLE ALMACENES;
DROP TABLE CLIENTES;

DROP SEQUENCE SEQPEDIDOS;
DROP SEQUENCE SEQCLIENTES;
-- DROP SEQUENCE SEQALMACENES;
-- DROP SEQUENCE SEQCATEGORIAS;
DROP SEQUENCE SEQPRODUCTOS;
DROP SEQUENCE SEQDETPEDIDOS;
